import { ContentAttribute } from './contentAttributes.model';
import { ConnectableObservable } from 'rxjs';

export interface Content extends ContentAttribute {
  id: number;
  name: string;
  caption: string;
  alternativeText: string;
  formats: {
    large: ContentAttribute;
    medium: ContentAttribute;
    small: ContentAttribute;
    thumbnail: ContentAttribute;
  };
  previewUrl: string;
  provider: string;
  provider_metadata: string;
  created_at: Date;
  updated_at: Date;
}

export const sampleContent: Content[] = [
  {
    id: 1,
    name: 'Maths',
    caption: 'Maths',
    alternativeText: '',
    formats: {
      large: {
        ext: '',
        url: 'assets/images/maths.jpg',
        hash: '',
        mime: '',
        size: 2000,
        height: 350,
        width: 350,
      },
      medium: {
        ext: '',
        url: 'assets/images/maths.jpg',
        hash: '',
        mime: '',
        size: 2000,
        height: 350,
        width: 350,
      },
      small: {
        ext: '',
        url: 'assets/images/maths.jpg',
        hash: '',
        mime: '',
        size: 2000,
        height: 350,
        width: 350,
      },
      thumbnail: {
        ext: '',
        url: 'assets/images/maths.jpg',
        hash: '',
        mime: '',
        size: 2000,
        height: 350,
        width: 350,
      },
    },
    previewUrl: '',
    provider: '',
    provider_metadata: '',
    created_at: new Date(),
    updated_at: new Date(),
    ext: '',
    url: 'assets/images/maths.jpg',
    hash: '',
    mime: '',
    size: 2000,
    height: 350,
    width: 350,
  },
  {
    id: 1,
    name: 'Science',
    caption: 'Science',
    alternativeText: '',
    formats: {
      large: {
        ext: '',
        url: 'assets/images/science.jpg',
        hash: '',
        mime: '',
        size: 2000,
        height: 350,
        width: 350,
      },
      medium: {
        ext: '',
        url: 'assets/images/science.jpg',
        hash: '',
        mime: '',
        size: 2000,
        height: 350,
        width: 350,
      },
      small: {
        ext: '',
        url: 'assets/images/science.jpg',
        hash: '',
        mime: '',
        size: 2000,
        height: 350,
        width: 350,
      },
      thumbnail: {
        ext: '',
        url: 'assets/images/science.jpg',
        hash: '',
        mime: '',
        size: 2000,
        height: 350,
        width: 350,
      },
    },
    previewUrl: '',
    provider: '',
    provider_metadata: '',
    created_at: new Date(),
    updated_at: new Date(),
    ext: '',
    url: 'assets/images/science.jpg',
    hash: '',
    mime: '',
    size: 2000,
    height: 350,
    width: 350,
  },
  {
    id: 1,
    name: 'History',
    caption: 'History',
    alternativeText: '',
    formats: {
      large: {
        ext: '',
        url: 'assets/images/history.jpg',
        hash: '',
        mime: '',
        size: 2000,
        height: 350,
        width: 350,
      },
      medium: {
        ext: '',
        url: 'assets/images/history.jpg',
        hash: '',
        mime: '',
        size: 2000,
        height: 350,
        width: 350,
      },
      small: {
        ext: '',
        url: 'assets/images/history.jpg',
        hash: '',
        mime: '',
        size: 2000,
        height: 350,
        width: 350,
      },
      thumbnail: {
        ext: '',
        url: 'assets/images/history.jpg',
        hash: '',
        mime: '',
        size: 2000,
        height: 350,
        width: 350,
      },
    },
    previewUrl: '',
    provider: '',
    provider_metadata: '',
    created_at: new Date(),
    updated_at: new Date(),
    ext: '',
    url: 'assets/images/history.jpg',
    hash: '',
    mime: '',
    size: 2000,
    height: 350,
    width: 350,
  },
  {
    id: 1,
    name: 'Computer Science',
    caption: 'Computer Science',
    alternativeText: '',
    formats: {
      large: {
        ext: '',
        url: 'assets/images/computer.jpg',
        hash: '',
        mime: '',
        size: 2000,
        height: 350,
        width: 350,
      },
      medium: {
        ext: '',
        url: 'assets/images/computer.jpg',
        hash: '',
        mime: '',
        size: 2000,
        height: 350,
        width: 350,
      },
      small: {
        ext: '',
        url: 'assets/images/computer.jpg',
        hash: '',
        mime: '',
        size: 2000,
        height: 350,
        width: 350,
      },
      thumbnail: {
        ext: '',
        url: 'assets/images/computer.jpg',
        hash: '',
        mime: '',
        size: 2000,
        height: 350,
        width: 350,
      },
    },
    previewUrl: '',
    provider: '',
    provider_metadata: '',
    created_at: new Date(),
    updated_at: new Date(),
    ext: '',
    url: 'assets/images/computer.jpg',
    hash: '',
    mime: '',
    size: 2000,
    height: 350,
    width: 350,
  },
];
